/* პათოლოგიის მოდული: ნოზოლოგია → აღწერა → განვითარების მექანიზმი (ეტაპები) → კლინიკა.
   fx — რა ხდება 3D მოდელზე თითოეულ ეტაპზე (იხ. engine.js → applyFx). */
const SB = t => 'https://www.ncbi.nlm.nih.gov/books/?term=' + encodeURIComponent('StatPearls ' + t);
const PM = t => 'https://pubmed.ncbi.nlm.nih.gov/?term=' + encodeURIComponent(t) + '&filter=pubt.review';

const NOSO_GROUPS = [
  ['cns', 'თავის ტვინი'],
  ['cord', 'ზურგის ტვინი / მოტორული ნეირონი'],
  ['cn', 'თავის ტვინის ნერვები'],
  ['nmj', 'ნერვ-კუნთოვანი სინაფსი'],
  ['pns', 'პერიფერიული ნერვები და ფესვები'],
];

const BRAIN = ['cortex', 'cerebellum', 'stem', 'deep', 'ventricle', 'artery', 'cranial', 'cord'];
const MOTOR_R = [{ c: 'left precentral' }, { c: 'left internal capsule' }, { c: '^peduncle of midbrain' }, { c: '^pons' }, { c: '^medulla oblongata' }, [-0.004, 1.52, -0.05], [-0.006, 1.43, -0.052], [-0.06, 1.40, -0.02], { snap: 'right median nerve', to: [-0.2, 1.2, 0] }, { snap: 'right median nerve', to: [-0.25, 0.9, 0.03] }];

const NOSOLOGY = [
// ============================== თავის ტვინი ==============================
{
  id: 'stroke', grp: 'cns', icd: 'I63', ka: 'იშემიური ინსულტი (მარცხენა შუა ტვინის არტერია)', en: 'Ischemic stroke — left MCA territory',
  desc: 'თავის ტვინის ნაწილის მწვავე ინფარქტი, რომელიც არტერიის დახშობით და სისხლის მიწოდების შეწყვეტით ვითარდება. შუა ტვინის არტერიის (MCA) აუზი ყველაზე ხშირად ზიანდება. ქვემოთ ნაჩვენებია მარცხენა (ჩვეულებრივ დომინანტური) ნახევარსფეროს ინფარქტი.',
  show: BRAIN.concat(['spinal', 'muscle', 'bone']), op: { bone: .1, cortex: .95 },
  steps: [
    { t: 'არტერიის ოკლუზია', x: 'თრომბი ან ემბოლი (მაგ. წინაგულების ფიბრილაციისას გულიდან ან საძილე არტერიის ათეროსკლეროზული ფოლაქიდან) ხშობს მარცხენა MCA-ს პროქსიმალურ (M1) სეგმენტს.',
      fx: { cam: 'brainL', show: ['cortex', 'cerebellum', 'stem', 'artery', 'deep'], op: { cortex: .25, cerebellum: .4 }, hl: [{ m: 'left middle cerebral', c: 'red' }], lesion: [{ at: { c: 'sphenoid part of left middle cerebral' }, r: .004 }], dim: true } },
    { t: 'იშემიური კასკადი', x: 'ATP-ის დეფიციტი → Na⁺/K⁺-ATPase-ის უკმარისობა → ციტოტოქსიური შეშუპება. გლუტამატის ჭარბი გამოყოფა და Ca²⁺-ის შემოდინება იწვევს ექსციტოტოქსიურ სიკვდილს. ინფარქტის ბირთვის გარშემო რჩება პენუმბრა: ფუნქციურად დათრგუნული, მაგრამ პოტენციურად გადარჩენადი ქსოვილი. სწორედ ის არის რეპერფუზიული თერაპიის სამიზნე.',
      fx: { cam: 'brainL', hl: [{ m: 'left (precentral|postcentral|inferior frontal|supramarginal|insula)|posterior part of left superior temporal|anterior part of left superior temporal', c: 'red' }, { m: 'left (middle frontal|angular|middle temporal)', c: 'amber' }], lesion: [{ at: { c: 'sphenoid part of left middle cerebral' }, r: .004 }], dim: true } },
    { t: 'ღრმა სტრუქტურები', x: 'ლენტიკულოსტრიული ტოტები M1-იდან მარაგავს ბაზალურ განგლიებს და შიგნითა კაფსულას. ამიტომ პროქსიმალური ოკლუზიისას ზიანდება კორტიკოსპინური გზაც კაფსულის უკანა ფეხში.',
      fx: { cam: 'deep', show: ['cortex', 'stem', 'deep', 'artery', 'ventricle'], op: { cortex: .08 }, hl: [{ m: 'left (internal capsule|putamen|caudate|globus pallidus)', c: 'red' }, { m: 'left middle cerebral', c: 'red' }], dim: true } },
    { t: 'ჯვარედინი გზა → კონტრალატერალური დეფიციტი', x: 'კორტიკოსპინური ბოჭკოების ≈85–90% მოგრძო ტვინის ქვედა ნაწილში, პირამიდების ჯვარედინზე, გადადის მოპირდაპირე მხარეს. ამიტომ მარცხენა ინფარქტი იწვევს მარჯვენამხრივ ცენტრალურ (UMN) ჰემიპარეზს. იმპულსი დაზიანების დონეზე წყდება.',
      fx: { cam: 'body', show: ['cortex', 'cerebellum', 'stem', 'cord', 'spinal', 'muscle', 'bone', 'legs'], op: { bone: .12 }, hl: [{ m: 'left (precentral|internal capsule)', c: 'red' }], grey: [{ m: '(right|mirrored)', g: ['spinal', 'muscle'] }, { m: '^right', g: ['legs'] }], flow: [{ path: MOTOR_R, c: 'amber', block: 1 }] } },
  ],
  clin: ['მარჯვენამხრივი ჰემიპარეზი: სახე და ხელი უფრო ძლიერ, ვიდრე ფეხი', 'მარჯვენამხრივი ჰემიჰიპესთეზია', 'აფაზია (ბროკას / ვერნიკეს / გლობალური), დომინანტური ნახევარსფეროს დაზიანებისას', 'მარჯვენამხრივი ჰომონიმური ჰემიანოპსია (ოპტიკური რადიაციის ჩართვისას)', 'თვალების დევიაცია დაზიანების მხარეს', 'მწვავე ფაზაში ატონია; შემდეგ სპასტიკურობა, ჰიპერრეფლექსია, ბაბინსკის ნიშანი'],
  refs: [['StatPearls: Middle Cerebral Artery Stroke', SB('middle cerebral artery stroke')], ['StatPearls: Ischemic Stroke', SB('ischemic stroke')]],
},
{
  id: 'parkinson', grp: 'cns', icd: 'G20', ka: 'პარკინსონის დაავადება', en: "Parkinson's disease",
  desc: 'ნეიროდეგენერაციული დაავადება. შავი სუბსტანციის (substantia nigra pars compacta) დოფამინერგული ნეირონების დაკარგვა არღვევს ბაზალური განგლიების მოტორულ მარყუჟს. მთავარი ნიშნებია ბრადიკინეზია, რიგიდობა და მოსვენების ტრემორი.',
  show: ['cortex', 'cerebellum', 'stem', 'deep', 'ventricle'], op: { cortex: .08, cerebellum: .25 },
  steps: [
    { t: 'α-სინუკლეინი და ნეირონების დაკარგვა', x: 'მისფოლდინგური α-სინუკლეინი აგრეგირდება ლევის სხეულებად. ზიანდება მიტოქონდრიული ფუნქცია და ლიზოსომური/ubiquitin-proteasome კლირენსი. შავი სუბსტანციის (შუა ტვინში) დოფამინერგული ნეირონები კვდება. მოტორული ნიშნები ჩნდება, როცა ნეირონების დაახლოებით ნახევარზე მეტი უკვე დაკარგულია.',
      fx: { cam: 'deep', hl: [{ m: '^midbrain|peduncle of midbrain', c: 'red' }], dim: true, note: 'შავი სუბსტანცია შუა ტვინის ნაწილია; მოდელში ცალკე მეშად არ არის გამოყოფილი.' } },
    { t: 'ნიგროსტრიატული დოფამინის დეფიციტი', x: 'შუა ტვინიდან სტრიატუმისკენ (კუდიანი ბირთვი + ნაჭუჭი) დოფამინის მიწოდება მცირდება; ნაჭუჭი ყველაზე ადრე და ყველაზე მეტად ზიანდება.',
      fx: { cam: 'deep', hl: [{ m: '^midbrain', c: 'red' }, { m: 'putamen|caudate', c: 'amber' }], flow: [{ path: [{ c: '^midbrain' }, { c: 'left putamen' }], c: 'teal', fade: 1 }, { path: [{ c: '^midbrain' }, { c: 'left caudate' }], c: 'teal', fade: 1 }], dim: true } },
    { t: 'პირდაპირი და არაპირდაპირი გზის დისბალანსი', x: 'D1-ზე დამოკიდებული პირდაპირი გზა სუსტდება, D2-ზე დამოკიდებული არაპირდაპირი გზა ძლიერდება. შედეგად ფერმკრთალი ბირთვის შიგნითა სეგმენტის (GPi) ინჰიბიციური გამოსავალი იზრდება და თალამუსი მეტად ითრგუნება.',
      fx: { cam: 'deep', hl: [{ m: 'putamen|caudate', c: 'amber' }, { m: 'globus pallidus', c: 'red' }, { m: 'thalamus', c: 'blue' }], flow: [{ path: [{ c: 'left putamen' }, { c: 'left globus pallidus' }, { c: 'left thalamus' }], c: 'red' }], dim: true } },
    { t: 'თალამო-კორტიკული აქტივაციის დაქვეითება', x: 'თალამუსი ნაკლებად ააქტიურებს მოტორულ და დამატებით მოტორულ ქერქს. მოძრაობის ინიციაცია და ამპლიტუდა მცირდება (ჰიპოკინეზია, ბრადიკინეზია).',
      fx: { cam: 'brainL', show: ['cortex', 'stem', 'deep', 'cerebellum'], op: { cortex: .55 }, hl: [{ m: 'thalamus', c: 'blue' }, { m: 'precentral|superior frontal', c: 'blue' }], flow: [{ path: [{ c: 'left thalamus' }, { c: 'left precentral' }], c: 'blue', fade: 1, slow: 1 }], dim: true } },
  ],
  clin: ['ბრადიკინეზია (აუცილებელი დიაგნოსტიკური კრიტერიუმი)', 'რიგიდობა, „კბილანა ბორბლის" ფენომენი', 'მოსვენების ტრემორი (4–6 Hz, „აბების გორება")', 'პოსტურული არასტაბილურობა (გვიანდელი ნიშანი)', 'ჰიპომიმია, მიკროგრაფია, ფეხის მოქნევით სიარული', 'არამოტორული: ჰიპოსმია, REM-ძილის ქცევის დარღვევა, ყაბზობა, დეპრესია'],
  refs: [['StatPearls: Parkinson Disease', SB('Parkinson disease')], ['MDS Clinical Diagnostic Criteria (Postuma 2015)', PM('MDS clinical diagnostic criteria Parkinson disease Postuma')]],
},
{
  id: 'alzheimer', grp: 'cns', icd: 'G30', ka: 'ალცჰაიმერის დაავადება', en: "Alzheimer's disease",
  desc: 'დემენციის ყველაზე ხშირი მიზეზი. ამილოიდური ფოლაქები და ტაუ ცილის ნეიროფიბრილარული გორგლები იწვევს სინაფსებისა და ნეირონების პროგრესირებად დაკარგვას. პროცესი იწყება მედიალური საფეთქლის წილიდან.',
  show: ['cortex', 'cerebellum', 'stem', 'deep', 'ventricle'], op: { cortex: .12, cerebellum: .3 },
  steps: [
    { t: 'ამილოიდ-β', x: 'ამილოიდის წინამორბედი ცილა (APP) β- და γ-სეკრეტაზებით იჭრება. წარმოიქმნება Aβ42, რომელიც ოლიგომერებად და ექსტრაცელულურ ფოლაქებად აგრეგირდება. ოლიგომერები სინაპტოტოქსიკურია.',
      fx: { cam: 'brainL', show: ['cortex', 'cerebellum', 'stem'], op: {}, hl: [{ m: 'temporal|angular|supramarginal|superior parietal|cingulate', c: 'amber' }], plaques: 'cortexL', dim: true } },
    { t: 'ტაუ და ბრაქის სტადიები', x: 'ჰიპერფოსფორილირებული ტაუ მიკროტუბულებს სცილდება და ნეიროფიბრილარულ გორგლებს ქმნის. ტაუ-პათოლოგია პროგნოზირებადი თანმიმდევრობით ვრცელდება: (ტრანს)ენტორინული ქერქი → ჰიპოკამპი → საფეთქლის ასოციაციური ქერქი → ნეოკორტექსი.',
      fx: { cam: 'deep', hl: [{ m: 'parahippocampal', c: 'red' }, { m: 'hippocampus', c: 'red' }], flow: [{ path: [{ c: 'left parahippocampal' }, { c: 'left hippocampus' }, { c: 'left inferior temporal' }, { c: 'left angular' }], c: 'red', slow: 1 }], dim: true } },
    { t: 'სინაფსური და ქოლინერგული დეფიციტი', x: 'სინაფსები იკარგება, მეინერტის ბაზალური ბირთვის ქოლინერგული ნეირონები დეგენერირდება და მიკროგლია ანთებით პასუხს ავითარებს. სწორედ ქოლინერგული დეფიციტი ხსნის აცეტილქოლინესთერაზას ინჰიბიტორების სიმპტომურ ეფექტს.',
      fx: { cam: 'deep', hl: [{ m: 'hippocampus|parahippocampal|fornix|amygdala', c: 'red' }], atrophy: [{ m: 'hippocampus|amygdala', k: .82 }], dim: true } },
    { t: 'ატროფია და პარკუჭების გაფართოება', x: 'ვითარდება ჰიპოკამპის, მედიალური საფეთქლის და თხემ-საფეთქლის ქერქის ატროფია. გვერდითი პარკუჭები და საფეთქლის რქები კომპენსატორულად ფართოვდება (hydrocephalus ex vacuo).',
      fx: { cam: 'deep', op: { cortex: .2 }, hl: [{ m: 'ventricle', c: 'blue' }, { m: 'temporal|angular|supramarginal|parahippocampal|hippocampus', c: 'red' }], atrophy: [{ m: 'hippocampus|amygdala|parahippocampal', k: .8 }, { m: 'temporal|angular|supramarginal', k: .93 }], swell: [{ m: 'lateral ventricle|third ventricle', k: 1.22 }] } },
  ],
  clin: ['ეპიზოდური მეხსიერების პროგრესირებადი დაქვეითება (ახალი ინფორმაციის დამახსოვრება)', 'ორიენტაციის დარღვევა დროსა და სივრცეში', 'ანომია, აფაზია, აპრაქსია, აგნოზია', 'აღმასრულებელი ფუნქციების დარღვევა', 'ქცევითი ცვლილებები: აპათია, აგზნება', 'MRI: ჰიპოკამპის ატროფია; PET/ლიქვორი: ამილოიდისა და ტაუს ბიომარკერები'],
  refs: [['StatPearls: Alzheimer Disease', SB('Alzheimer disease')], ['Braak & Braak — neuropathological staging', PM('Braak staging neurofibrillary tangles')]],
},
{
  id: 'ms', grp: 'cns', icd: 'G35', ka: 'გაფანტული სკლეროზი', en: 'Multiple sclerosis',
  desc: 'ცნს-ის ქრონიკული იმუნური დაავადება. მიელინი და ოლიგოდენდროციტები ზიანდება და დემიელინიზაციის ფოლაქები წარმოიქმნება, რომლებიც „გაფანტულია" დროსა და სივრცეში. პერიფერიული ნერვები არ ზიანდება, რადგან მათ შვანის უჯრედების მიელინი აქვთ.',
  show: ['cortex', 'cerebellum', 'stem', 'deep', 'ventricle', 'cord'], op: { cortex: .07, cerebellum: .3 },
  steps: [
    { t: 'იმუნური აქტივაცია', x: 'გენეტიკური წინასწარგანწყობის (HLA-DRB1*15:01) და გარემო ფაქტორების (EBV-ინფექცია, D ვიტამინის დეფიციტი, მოწევა) ფონზე აქტიურდება ავტორეაქტიული CD4⁺ Th1/Th17 ლიმფოციტები და B უჯრედები.',
      fx: { cam: 'deep', hl: [], dim: true } },
    { t: 'ბარიერის გავლა და დემიელინიზაცია', x: 'ლიმფოციტები ჰემატოენცეფალურ ბარიერს კვეთს. მაკროფაგები და მიკროგლია ანგრევს მიელინს და აზიანებს ოლიგოდენდროციტებს. ფოლაქების ტიპური ლოკალიზაციაა პერივენტრიკულური (დოუსონის თითები), იუქსტაკორტიკალური, ინფრატენტორიული და ზურგის ტვინი.',
      fx: { cam: 'deep', hl: [{ m: 'lateral ventricle', c: 'blue' }, { m: 'corpus callosum', c: 'amber' }], plaques: 'ms', dim: true } },
    { t: 'გატარების ბლოკი', x: 'დემიელინიზებულ აქსონში სალტატორული გატარება ირღვევა: იმპულსი ნელდება ან საერთოდ ჩერდება. ტიპური ადრეული გამოვლინებაა მხედველობის ნერვის ნევრიტი. რემიელინიზაცია და Na⁺ არხების გადანაწილება ნაწილობრივ აღადგენს ფუნქციას, რაც რემისიის სახით ვლინდება.',
      fx: { cam: 'headFront', show: ['cortex', 'stem', 'deep', 'cranial', 'ventricle'], op: { cortex: .06 }, hl: [{ m: 'optic (nerve|chiasm|tract)', c: 'red' }], plaques: 'ms', flow: [{ path: [{ snap: 'left optic nerve', to: [0.02, 1.61, 0.05] }, { c: 'optic chiasm' }, { c: 'left optic tract' }], c: 'amber', block: 1 }], dim: true } },
    { t: 'აქსონური დეგენერაცია → პროგრესირება', x: 'განმეორებითი ანთება და ქრონიკული აქტიური („მოცურავე") ფოლაქები იწვევს აქსონების დაკარგვას და ატროფიას. ამ ეტაპზე დეფიციტი უკვე შეუქცევადია და ვითარდება მეორადი პროგრესირება.',
      fx: { cam: 'spineBack', show: ['cortex', 'cerebellum', 'stem', 'cord', 'deep', 'bone'], op: { bone: .12, cortex: .5 }, hl: [{ m: 'spinal cord', c: 'amber' }], plaques: 'msCord', dim: true } },
  ],
  clin: ['ოპტიკური ნევრიტი: ცალმხრივი მხედველობის დაქვეითება, ტკივილი თვალის მოძრაობისას', 'სენსორული დარღვევები, ლერმიტის ნიშანი', 'სპასტიკური პარეზი, ჰიპერრეფლექსია', 'ნათხემისმიერი ატაქსია, ინტენციური ტრემორი', 'ინტერნუკლეარული ოფთალმოპლეგია (MLF)', 'უჰტჰოფის ფენომენი: გაუარესება სიცხეზე', 'დიაგნოზი: მაკდონალდის კრიტერიუმები (2017), MRI, ოლიგოკლონური ზოლები ლიქვორში'],
  refs: [['StatPearls: Multiple Sclerosis', SB('multiple sclerosis')], ['McDonald criteria 2017 (Thompson et al.)', PM('2017 McDonald criteria multiple sclerosis Thompson')]],
},
{
  id: 'tle', grp: 'cns', icd: 'G40', ka: 'მედიალური საფეთქლის წილის ეპილეფსია', en: 'Mesial temporal lobe epilepsy (hippocampal sclerosis)',
  desc: 'ზრდასრულებში ყველაზე ხშირი ფოკალური ეპილეფსია. ეპილეფსიური კერა ჰიპოკამპში ან ამიგდალაშია და ხშირად უკავშირდება ჰიპოკამპის სკლეროზს. ხშირად რეზისტენტულია მედიკამენტების მიმართ, ამიტომ ქირურგიული მკურნალობის კანდიდატია.',
  show: ['cortex', 'cerebellum', 'stem', 'deep', 'ventricle'], op: { cortex: .1, cerebellum: .3 },
  steps: [
    { t: 'ჰიპოკამპის სკლეროზი', x: 'CA1 და CA3 ველებში პირამიდული ნეირონები იკარგება და ვითარდება გლიოზი. ხშირად ანამნეზშია ადრეული ბავშვობის ხანგრძლივი ფებრილური გულყრა ან სხვა დაზიანება.',
      fx: { cam: 'deep', hl: [{ m: 'left hippocampus', c: 'red' }], atrophy: [{ m: 'left hippocampus', k: .85 }], dim: true } },
    { t: 'ქსელის რეორგანიზაცია', x: 'კბილა ხვეულის გრანულური უჯრედების ხავსისებრი ბოჭკოები ახალ, აგზნებად განშტოებებს იზრდის (mossy fiber sprouting). ინჰიბიციური ინტერნეირონები იკარგება და GABA-ერგული დათრგუნვა სუსტდება, რაც ქსელს ჰიპერაგზნებადს ხდის.',
      fx: { cam: 'deep', hl: [{ m: 'left hippocampus', c: 'red' }, { m: 'left (amygdala|parahippocampal)', c: 'amber' }], wave: { at: { c: 'left hippocampus' }, r: .018, c: 'red' }, dim: true } },
    { t: 'გულყრის გავრცელება', x: 'ჰიპერსინქრონული განმუხტვა ჰიპოკამპიდან ვრცელდება ამიგდალაზე, საფეთქლის ნეოკორტექსსა და კუნძულზე. აქედან შეიძლება გადავიდეს კონტრალატერალურ ნახევარსფეროზე და თალამო-კორტიკული ქსელით გენერალიზდეს.',
      fx: { cam: 'brainL', show: ['cortex', 'cerebellum', 'stem', 'deep'], op: { cortex: .45 }, hl: [{ m: 'left (hippocampus|amygdala)', c: 'red' }, { m: 'left .*(temporal|insula|fusiform)', c: 'amber' }], wave: { at: { c: 'left hippocampus' }, r: .05, c: 'red' }, dim: true } },
    { t: 'კლინიკური გამოვლინება', x: 'გულყრა ხშირად აურით იწყება: ეპიგასტრიული აღმავალი შეგრძნება, déjà vu ან შიში. შემდეგ ვითარდება ფოკალური გულყრა ცნობიერების დარღვევით, ორო-ალიმენტარული და ხელის ავტომატიზმებით, რასაც მოსდევს პოსტიქტალური დაბნეულობა. დომინანტური მხარის კერისას შესაძლოა პოსტიქტალური აფაზია.',
      fx: { cam: 'brainL', hl: [{ m: 'left (hippocampus|amygdala|parahippocampal)|left .*temporal', c: 'red' }, { m: 'right .*temporal', c: 'amber' }], wave: { at: { c: 'left hippocampus' }, r: .08, c: 'red' }, dim: true } },
  ],
  clin: ['აურა: ეპიგასტრიული შეგრძნება, déjà vu, შიში, ყნოსვითი ილუზია', 'ფოკალური გულყრა ცნობიერების დარღვევით', 'ავტომატიზმები: ღეჭვა, ტუჩების წკლაპუნი, ხელის მოძრაობები', 'პოსტიქტალური დაბნეულობა; დომინანტური კერისას აფაზია', 'MRI: ჰიპოკამპის ატროფია და T2/FLAIR ჰიპერინტენსივობა', 'მედიკამენტრეზისტენტულ შემთხვევაში — წინა საფეთქლის ლობექტომია ან ამიგდალოჰიპოკამპექტომია'],
  refs: [['StatPearls: Temporal Lobe Seizure', SB('temporal lobe seizure')], ['ILAE — hippocampal sclerosis classification', PM('ILAE hippocampal sclerosis classification Blumcke')]],
},
// ============================== ზურგის ტვინი ==============================
{
  id: 'als', grp: 'cord', icd: 'G12.2', ka: 'გვერდითი ამიოტროფიული სკლეროზი (ALS)', en: 'Amyotrophic lateral sclerosis',
  desc: 'ზედა (ქერქი) და ქვედა (ღეროს ბირთვები, ზურგის ტვინის წინა რქები) მოტორული ნეირონების პროგრესირებადი დეგენერაცია. სენსორიკა და თვალის მოძრაობები, როგორც წესი, დიდხანს შენარჩუნებულია.',
  show: ['cortex', 'cerebellum', 'stem', 'deep', 'cord', 'spinal', 'muscle', 'bone', 'legs'], op: { bone: .12 },
  steps: [
    { t: 'მოლეკულური მექანიზმები', x: 'შემთხვევების დაახლოებით 97%-ში ციტოპლაზმაში გროვდება TDP-43 ცილა. ოჯახურ ფორმებში (≈10%) გვხვდება C9orf72, SOD1, FUS და TARDBP მუტაციები. დამატებით მოქმედებს გლუტამატური ექსციტოტოქსიკურობა, ოქსიდაციური სტრესი, აქსონური ტრანსპორტის დარღვევა და გლიური ანთება.',
      fx: { cam: 'brainL', show: ['cortex', 'cerebellum', 'stem'], op: {}, hl: [{ m: 'precentral', c: 'red' }], dim: true } },
    { t: 'ზედა მოტორული ნეირონი', x: 'წინაცენტრალური ხვეულის ბეცის უჯრედები და კორტიკოსპინური გზა (შიგნითა კაფსულა, ტვინის ფეხი, ხიდი, პირამიდები) დეგენერირდება. ზურგის ტვინის გვერდითი სვეტების სკლეროზი დაავადების სახელშია ასახული.',
      fx: { cam: 'deep', show: ['cortex', 'stem', 'deep', 'cord'], op: { cortex: .15 }, hl: [{ m: 'precentral', c: 'red' }, { m: 'internal capsule|peduncle|pons|medulla', c: 'amber' }], flow: [{ path: [{ c: 'left precentral' }, { c: 'left internal capsule' }, { c: '^pons' }, { c: '^medulla oblongata' }, [0, 1.45, -0.05]], c: 'red', fade: 1 }], dim: true } },
    { t: 'ქვედა მოტორული ნეირონი', x: 'ზურგის ტვინის წინა რქებისა და ღეროს მოტორული ბირთვების (ბულბური ფორმა) ნეირონები კვდება. კუნთი დენერვირდება და ჩნდება ფასციკულაციები.',
      fx: { cam: 'spineBack', show: ['stem', 'cord', 'spinal', 'bone', 'legs', 'cerebellum', 'cortex'], op: { bone: .12 }, hl: [{ m: 'spinal cord|medulla', c: 'red' }], grey: [{ m: '.', g: ['spinal', 'legs'] }], dim: true } },
    { t: 'ატროფია + ჰიპერრეფლექსია', x: 'ALS-ის დამახასიათებელი ნიშანია UMN და LMN ნიშნების ერთდროულად არსებობა ერთსა და იმავე სეგმენტში. სიკვდილის მთავარი მიზეზი სუნთქვის კუნთების სისუსტეა.',
      fx: { cam: 'body', show: ['cortex', 'stem', 'cord', 'spinal', 'muscle', 'bone', 'legs', 'skin'], op: { bone: .1 }, hl: [{ m: 'precentral|spinal cord', c: 'red' }], atrophy: [{ m: '.', g: ['muscle'], k: .8 }], grey: [{ m: '.', g: ['muscle'] }] } },
  ],
  clin: ['ასიმეტრიული დისტალური სისუსტე (ხშირად მტევანი, ტენარი)', 'კუნთების ატროფია, ფასციკულაციები, კრამპები', 'ჰიპერრეფლექსია და სპასტიკურობა ატროფირებულ კიდურზე', 'ბულბური ფორმა: დიზართრია, დისფაგია', 'სენსორიკა, თვალის მოძრაობები და სფინქტერები შენარჩუნებულია', 'ENMG: დენერვაციის ნიშნები 3–4 რეგიონში (El Escorial / Gold Coast კრიტერიუმები)'],
  refs: [['StatPearls: Amyotrophic Lateral Sclerosis', SB('amyotrophic lateral sclerosis')], ['Gold Coast criteria (Shefner 2020)', PM('Gold Coast criteria ALS Shefner')]],
},
{
  id: 'sci', grp: 'cord', icd: 'S24.1', ka: 'ზურგის ტვინის ტრავმული დაზიანება (T5)', en: 'Traumatic spinal cord injury — thoracic',
  desc: 'მალის მოტეხილობა-ამოვარდნილობისას ზურგის ტვინი მექანიკურად ზიანდება, რასაც მეორადი ბიოქიმიური დაზიანება მოსდევს. სრული დაზიანებისას დონის ქვემოთ ყველა მოტორული, სენსორული და ავტონომიური ფუნქცია იკარგება.',
  show: ['cortex', 'cerebellum', 'stem', 'cord', 'spinal', 'bone', 'legs', 'muscle', 'skin'], op: { bone: .2 },
  steps: [
    { t: 'პირველადი დაზიანება', x: 'მალის სხეულის ფრაგმენტი ან ამოვარდნილობა ზურგის ტვინს კუმშავს, აკონტუზიებს ან წყვეტს. აქსონები და სისხლძარღვები დაზიანების მომენტშივე ზიანდება.',
      fx: { cam: 'spineLesion', show: ['cord', 'bone', 'spinal'], op: { bone: .3 }, hl: [{ m: 'fifth thoracic vertebra', c: 'amber', g: ['bone'] }], lesion: [{ at: { y: 'fifth thoracic vertebra', x: 0, z: -0.052 }, r: .012 }], dim: true } },
    { t: 'მეორადი დაზიანება', x: 'საათებიდან დღეებამდე პერიოდში ვითარდება იშემია, შეშუპება, ჰემორაგია, გლუტამატური ექსციტოტოქსიკურობა, ანთება, თავისუფალი რადიკალები, ოლიგოდენდროციტების აპოპტოზი. ამ პროცესებით დაზიანების ზონა თავდაპირველზე უფრო ფართოვდება.',
      fx: { cam: 'spineLesion', hl: [{ m: 'spinal cord', c: 'red', where: { near: { y: 'fifth thoracic vertebra', x: 0, z: -0.052 }, r: .045 } }], lesion: [{ at: { y: 'fifth thoracic vertebra', x: 0, z: -0.052 }, r: .02 }], dim: true } },
    { t: 'სპინური შოკი', x: 'დონის ქვემოთ ტვინიდან დაღმავალი იმპულსები აღარ აღწევს. თავიდან ვითარდება ატონია და არეფლექსია (სპინური შოკი). დღეების და კვირების შემდეგ ყალიბდება UMN სურათი: სპასტიკურობა, ჰიპერრეფლექსია, ბაბინსკის ნიშანი.',
      fx: { cam: 'body', show: ['cortex', 'cerebellum', 'stem', 'cord', 'spinal', 'bone', 'legs', 'muscle'], op: { bone: .12 }, hl: [{ m: 'spinal cord', c: 'red', where: { below: { y: 'fifth thoracic vertebra' } } }], grey: [{ m: '.', g: ['legs'] }, { m: 'gastrocnemius|soleus|tibialis|fibularis|extensor (digitorum|hallucis) longus|rectus femoris|vastus|biceps femoris|semitendinosus|gluteus', g: ['muscle'] }], flow: [{ path: [{ c: 'left precentral' }, { c: 'left internal capsule' }, { c: '^pons' }, { c: '^medulla oblongata' }, [0, 1.45, -0.05], { y: 'fifth thoracic vertebra', x: 0, z: -0.052 }, [0, 1.1, -0.06], [0.04, 0.93, -0.088]], c: 'amber', block: 1 }] } },
    { t: 'ავტონომიური შედეგები', x: 'T6-ზე ზემოთ დაზიანებისას არსებობს ავტონომიური დისრეფლექსიის რისკი: დონის ქვემოთ მომდინარე ტკივილოვანი სტიმული (მაგ. შარდის ბუშტის გადავსება) იწვევს უკონტროლო სიმპათიკურ პასუხს და მძიმე ჰიპერტენზიას. გარდა ამისა, ვითარდება ნეიროგენული შარდის ბუშტი და ნაწლავი.',
      fx: { cam: 'body', hl: [{ m: 'spinal cord', c: 'red', where: { below: { y: 'fifth thoracic vertebra' } } }], grey: [{ m: '.', g: ['legs'] }, { m: 'gastrocnemius|soleus|tibialis|fibularis|extensor (digitorum|hallucis) longus|rectus femoris|vastus|biceps femoris|semitendinosus|gluteus', g: ['muscle'] }], lesion: [{ at: { y: 'fifth thoracic vertebra', x: 0, z: -0.052 }, r: .014 }] } },
  ],
  clin: ['სრული დაზიანება (ASIA A): ქვედა პარაპლეგია, მგრძნობელობის დაკარგვა T5 დერმატომის ქვემოთ', 'მწვავედ: სპინური შოკი (ატონია, არეფლექსია); შემდეგ: სპასტიკურობა, ჰიპერრეფლექსია', 'ნეიროგენული შარდის ბუშტი და ნაწლავი', 'T6-ზე ზემოთ: ავტონომიური დისრეფლექსიის რისკი', 'ნეიროგენული შოკი მაღალი დაზიანებისას (ჰიპოტენზია, ბრადიკარდია)', 'შეფასება: ISNCSCI / ASIA Impairment Scale'],
  refs: [['StatPearls: Spinal Cord Injuries', SB('spinal cord injuries')], ['ISNCSCI (ASIA) standards', PM('International Standards Neurological Classification Spinal Cord Injury revision')]],
},
// ============================== თავის ტვინის ნერვები ==============================
{
  id: 'bell', grp: 'cn', icd: 'G51.0', ka: 'ბელის დამბლა (სახის ნერვის იდიოპათიური ნევროპათია)', en: "Bell's palsy",
  desc: 'სახის ნერვის (VII) მწვავე, ცალმხრივი, ქვედა მოტორული ნეირონის ტიპის დაზიანება. ზიანდება დაზიანების მხარის ყველა მიმიკური კუნთი, შუბლის ჩათვლით. ინსულტისგან განსხვავებით, შუბლიც ზიანდება, რადგან დაზიანება ნერვის დონეზეა და არა ქერქში.',
  show: ['cortex', 'cerebellum', 'stem', 'cranial', 'bone', 'muscle', 'skin'], op: { bone: .15, cortex: .5 },
  steps: [
    { t: 'ტრიგერი', x: 'ყველაზე სავარაუდო მიზეზია HSV-1-ის რეაქტივაცია მუხლისებრ განგლიონში (ganglion geniculi). განიხილება VZV-ც. მექანიზმი ბოლომდე დადგენილი არ არის.',
      fx: { cam: 'faceL', show: ['stem', 'cranial', 'bone', 'cerebellum'], op: { bone: .15 }, hl: [{ m: 'trunk of left facial', c: 'amber' }], lesion: [{ at: { snap: 'trunk of left facial', to: [0.02, 1.58, -0.01] }, r: .004 }], dim: true } },
    { t: 'შეშუპება ვიწრო არხში', x: 'ანთება და შეშუპება ვითარდება სახის ნერვის ძვლოვან არხში (canalis facialis). ყველაზე ვიწრო ადგილი ლაბირინთული სეგმენტია, სადაც შეშუპებულ ნერვს ადგილი არ რჩება. კომპრესია იწვევს იშემიას და დემიელინიზაციას, მძიმე შემთხვევაში კი აქსონურ დეგენერაციას.',
      fx: { cam: 'faceL', hl: [{ m: 'trunk of left facial', c: 'red' }], lesion: [{ at: { snap: 'trunk of left facial', to: [0.02, 1.58, -0.01] }, r: .006 }], dim: true } },
    { t: 'იმპულსის ბლოკი ყველა ტოტში', x: 'დაზიანება ტოტების განშტოებამდეა, ამიტომ იმპულსი ვერ აღწევს ვერცერთ ტოტს: საფეთქლის, ყვრიმალის, ლოყის, ქვედა ყბის კიდის და კისრის ტოტს. ყველა მიმიკური კუნთი დუნდება.',
      fx: { cam: 'faceL', show: ['stem', 'cranial', 'bone', 'muscle', 'cerebellum'], hl: [{ m: 'left facial|left posterior auricular', c: 'red' }], grey: [{ m: 'left platysma', g: ['muscle'] }], flow: [{ path: [{ c: '^pons' }, { snap: 'trunk of left facial', to: [0.02, 1.58, -0.01] }, { snap: 'trunk of left facial', to: [0.045, 1.53, 0.0] }], c: 'amber', block: 1 }], dim: true } },
    { t: 'თანმხლები ნიშნები', x: 'დაზიანების დონიდან გამომდინარე შეიძლება დაემატოს: ჰიპერაკუზია (m. stapedius), ენის წინა 2/3-ზე გემოს დარღვევა (chorda tympani), ცრემლდენის შემცირება (დიდი კლდოვანი ნერვი). შემთხვევების დიდ უმრავლესობაში სრული ან თითქმის სრული აღდგენა ხდება.',
      fx: { cam: 'faceL', hl: [{ m: 'left facial', c: 'red' }, { m: 'left (lingual|mandibular)', c: 'amber' }], dim: true } },
  ],
  clin: ['მწვავე (≤72 სთ) ცალმხრივი სახის სისუსტე, შუბლის ჩათვლით', 'ლაგოფთალმი, ბელის ფენომენი (თვალის კაკალი ზემოთ ბრუნავს)', 'პირის კუთხის დაწევა, ნასოლაბიალური ნაოჭის დაგლუვება', 'ჰიპერაკუზია, გემოს დარღვევა, ყურის უკან ტკივილი', 'მკურნალობა: კორტიკოსტეროიდები პირველი 72 საათის განმავლობაში; რქოვანას დაცვა', 'დიფერენცირება: ინსულტი (შუბლი შენარჩუნებულია), რამსეი-ჰანტის სინდრომი, ლაიმის დაავადება'],
  refs: [['StatPearls: Bell Palsy', SB('Bell palsy')], ['AAO-HNS Clinical Practice Guideline: Bell\'s Palsy', PM('clinical practice guideline Bell palsy Baugh')]],
},
{
  id: 'tn', grp: 'cn', icd: 'G50.0', ka: 'სამწვერა ნერვის ნევრალგია', en: 'Trigeminal neuralgia',
  desc: 'სამწვერა ნერვის ერთი ან რამდენიმე ტოტის ზონაში, უმეტესად V2/V3-ში, ცალმხრივი, ელექტროშოკისმაგვარი, წამიერი ტკივილის შეტევები. შეტევებს უბრალო შეხება ან ღეჭვა იწვევს.',
  show: ['cortex', 'cerebellum', 'stem', 'cranial', 'artery', 'bone'], op: { bone: .12, cortex: .2, cerebellum: .5 },
  steps: [
    { t: 'ნეიროვასკულური კომპრესია', x: 'კლასიკურ ფორმაში არტერიული მარყუჟი, ყველაზე ხშირად ნათხემის ზედა არტერია (SCA), აწვება ნერვის ფესვს ხიდში შესვლის ზონაში (root entry zone). ამ მონაკვეთზე ცენტრალური მიელინი პერიფერიულზე გადადის და ყველაზე მოწყვლადია.',
      fx: { only: [{ g: 'cranial', m: 'trigeminal|maxillary|mandibular|facial|vestibulocochlear|abducens|trunk of .*oculomotor|trochlear' }, { g: 'artery', m: 'cerebellar|basilar|vertebral|posterior cerebral' }], cam: 'tn', show: ['stem', 'cerebellum', 'cranial', 'artery'], op: { cerebellum: .35 }, hl: [{ m: 'left superior cerebellar', c: 'red', g: ['artery'] }, { m: 'trunk of left trigeminal', c: 'amber' }], lesion: [{ at: { c: 'trunk of left trigeminal' }, r: .004 }], dim: true } },
    { t: 'ფოკალური დემიელინიზაცია', x: 'ქრონიკული პულსაციური კომპრესია იწვევს ფოკალურ დემიელინიზაციას. ამის შედეგად გვხვდება ეფაპტური (ephaptic) გადაცემა მეზობელ ბოჭკოებს შორის და ექტოპიური, სპონტანური განმუხტვები.',
      fx: { only: [{ g: 'cranial', m: 'trigeminal|maxillary|mandibular|facial|vestibulocochlear|abducens|trunk of .*oculomotor|trochlear' }, { g: 'artery', m: 'cerebellar|basilar|vertebral|posterior cerebral' }], cam: 'tn', hl: [{ m: 'trunk of left trigeminal', c: 'red' }, { m: 'left superior cerebellar', c: 'red', g: ['artery'] }], lesion: [{ at: { c: 'trunk of left trigeminal' }, r: .005 }], wave: { at: { c: 'trunk of left trigeminal' }, r: .012, c: 'amber' }, dim: true } },
    { t: 'შეხება → ტკივილი', x: 'მსხვილი Aβ (შეხების) ბოჭკოების აქტივაცია ეფაპტურად გადაეცემა Aδ/C ნოციცეპტიურ ბოჭკოებს. ამიტომ ტრიგერ-ზონებზე მსუბუქი შეხება, ღეჭვა, საუბარი ან კბილის გახეხვა ტკივილის შეტევას იწვევს.',
      fx: { cam: 'faceL', show: ['stem', 'cranial', 'bone', 'cerebellum', 'artery'], hl: [{ m: 'left (maxillary|mandibular|infra-?orbital|alveolar|lingual|mental|buccal nerve|auriculotemporal)', c: 'red' }, { m: 'trunk of left trigeminal', c: 'red' }], flow: [{ path: [{ c: 'trunk of left trigeminal' }, { c: 'trunk of left maxillary' }], c: 'red' }, { path: [{ c: 'trunk of left trigeminal' }, { c: 'left mandibular nerve' }, { c: 'left mental' }], c: 'red' }], dim: true } },
    { t: 'მეორადი ფორმები', x: 'ახალგაზრდა ასაკში, ორმხრივი ან სენსორული დეფიციტით მიმდინარე შემთხვევაში საჭიროა მეორადი მიზეზის გამორიცხვა. ასეთი მიზეზებია გაფანტული სკლეროზის ფოლაქი ფესვის შესვლის ზონაში ან ხიდ-ნათხემის კუთხის სიმსივნე. აუცილებელია MRI.',
      fx: { only: [{ g: 'cranial', m: 'trigeminal|maxillary|mandibular|facial|vestibulocochlear|abducens|trunk of .*oculomotor|trochlear' }, { g: 'artery', m: 'cerebellar|basilar|vertebral|posterior cerebral' }], cam: 'tn', hl: [{ m: 'trunk of left trigeminal', c: 'amber' }, { m: '^pons', c: 'blue' }], dim: true } },
  ],
  clin: ['ცალმხრივი, ელექტროშოკისმაგვარი ტკივილი, წამებიდან 2 წუთამდე', 'V2/V3 ზონა ყველაზე ხშირად; V1 იშვიათად', 'ტრიგერები: შეხება, ღეჭვა, საუბარი, კბილის გახეხვა, ქარი', 'შეტევებს შორის ტკივილი არ არის (კლასიკური ფორმა)', 'ნევროლოგიური დეფიციტი, როგორც წესი, არ არის', 'პირველი რიგის პრეპარატი: კარბამაზეპინი (Carbamazepine) ან ოქსკარბაზეპინი (Oxcarbazepine); რეზისტენტობისას მიკროვასკულური დეკომპრესია'],
  refs: [['StatPearls: Trigeminal Neuralgia', SB('trigeminal neuralgia')], ['ICHD-3 (International Classification of Headache Disorders)', 'https://ichd-3.org/']],
},
// ============================== პერიფერიული ==============================
{
  id: 'mg', grp: 'nmj', icd: 'G70.0', ka: 'მიასთენია გრავისი', en: 'Myasthenia gravis',
  desc: 'ნერვ-კუნთოვანი გადაცემის აუტოიმუნური დაავადება, პოსტსინაფსური დაზიანებით. გენერალიზებული ფორმის დაახლოებით 85%-ში ანტისხეულები მიმართულია აცეტილქოლინის რეცეპტორის (AChR) წინააღმდეგ, ნაკლებად ხშირად MuSK-ის ან LRP4-ის წინააღმდეგ. მთავარი ნიშანია დაღლადი სისუსტე: ძლიერდება დატვირთვით და მცირდება მოსვენებით.',
  show: ['cortex', 'cerebellum', 'stem', 'cranial', 'cord', 'spinal', 'legs', 'muscle', 'bone', 'skin'], op: { bone: .12 },
  steps: [
    { t: 'ანტისხეულები AChR-ის წინააღმდეგ', x: 'აუტოიმუნური პროცესი ხშირად თიმუსთან არის დაკავშირებული: თიმუსის ჰიპერპლაზია ხშირია, თიმომა გვხვდება დაახლოებით 10–15%-ში. CD4⁺ T ლიმფოციტების დახმარებით B უჯრედები IgG1/IgG3 ანტისხეულებს გამოიმუშავებენ ნიკოტინური რეცეპტორის α ქვეერთეულის მთავარი იმუნოგენური რეგიონის წინააღმდეგ.',
      fx: { micro: { view: 'rec', anim: 'mg_ab' }, note: 'სქემატური უჯრედული დონე; ACh-ის რეცეპტორები ბოლო ფირფიტაზე.' } },
    { t: 'რეცეპტორების დაკარგვა', x: 'ანტისხეულები სამი გზით ამცირებს ფუნქციური რეცეპტორების რაოდენობას. (1) კომპლემენტი აქტიურდება, მემბრანის შემტევი კომპლექსი (MAC) აზიანებს პოსტსინაფსურ მემბრანას და მისი ნაოჭები სიმარტივდება. (2) ანტისხეულები რეცეპტორებს ერთმანეთთან აკავშირებს, რაც მათ ენდოციტოზსა და დაშლას აჩქარებს (ანტიგენური მოდულაცია). (3) იშვიათად ანტისხეული პირდაპირ ბლოკავს ACh-ის დაკავშირების ადგილს. ACh ნორმალურად გამოიყოფა, მაგრამ პასუხი სუსტია.',
      fx: { micro: { view: 'rec', anim: 'mg_fewrec' } } },
    { t: 'უსაფრთხოების ფაქტორის შემცირება → დაღლადობა', x: 'ნორმაში ბოლო ფირფიტის პოტენციალი (EPP) ზღურბლს დიდი მარაგით აჭარბებს (უსაფრთხოების ფაქტორი). რეცეპტორების დაკარგვის შემდეგ EPP ზღურბლს მცირედ აჭარბებს. განმეორებითი სტიმულაციისას ACh-ის გამოყოფა ფიზიოლოგიურადაც მცირდება და EPP ზოგიერთ ბოჭკოში ზღურბლს ქვემოთ ეცემა. ამის შედეგია დაღლადი სისუსტე, ENMG-ზე კი 3 Hz-იანი რითმული სტიმულაციისას >10%-იანი დეკრემენტი.',
      fx: { micro: { view: 'rec', anim: 'mg_rundown' }, chart: 'epp' } },
    { t: 'კლინიკური განაწილება', x: 'ყველაზე ხშირად ზიანდება თვალის გარეთა კუნთები (პტოზი, დიპლოპია), ბულბური (დისფაგია, დიზართრია, ღეჭვისას დაღლა) და კიდურების პროქსიმალური კუნთები. სუნთქვის კუნთების ჩართვა მიასთენიურ კრიზს იწვევს. მგრძნობელობა და რეფლექსები შენარჩუნებულია.',
      fx: { cam: 'body', show: ['cortex', 'cerebellum', 'stem', 'cranial', 'cord', 'spinal', 'legs', 'muscle', 'bone'], hl: [{ m: 'oculomotor|trochlear|abducens|nerve to .*(rectus|oblique|levator)|facial|glossopharyngeal|vagus|hypoglossal', c: 'amber', g: ['cranial'] }, { m: '(deltoid|biceps brachii|triceps brachii|rectus femoris|vastus|gluteus|biceps femoris|semitendinosus)', c: 'amber', g: ['muscle'] }, { m: 'phrenic', c: 'red', g: ['spinal'] }], dim: true } },
  ],
  clin: ['დაღლადი სისუსტე, უარესდება საღამოს და დატვირთვით', 'პტოზი, დიპლოპია (≈ 50%-ში პირველი ნიშანი)', 'ბულბური ნიშნები; მიასთენიური კრიზი — სუნთქვის უკმარისობა', 'მგრძნობელობა და რეფლექსები ნორმალურია', 'დიაგნოზი: anti-AChR / anti-MuSK ანტისხეულები, RNS-დეკრემენტი, ერთი ბოჭკოს EMG (jitter), ყინულის ტესტი; გულმკერდის CT (თიმომა)', 'მკურნალობა: პირიდოსტიგმინი (Pyridostigmine), კორტიკოსტეროიდები, აზათიოპრინი (Azathioprine), C5 ინჰიბიტორები (Eculizumab, Ravulizumab), FcRn ანტაგონისტი (Efgartigimod), თიმექტომია; კრიზისას IVIG ან პლაზმაფერეზი', 'ფარმაცევტისთვის: ამწვავებს ამინოგლიკოზიდები, ფტორქინოლონები, მაკროლიდები, მაგნიუმი (iv), β-ბლოკერები, ბოტულინის ტოქსინი; ზემგრძნობელობა არადეპოლარიზებელი მიორელაქსანტების მიმართ'],
  refs: [['StatPearls: Myasthenia Gravis', SB('myasthenia gravis')], ['International consensus guidance for MG (Narayanaswami 2021)', PM('International consensus guidance for management of myasthenia gravis 2020 update Narayanaswami')]],
},
{
  id: 'lems', grp: 'nmj', icd: 'G73.1 / G70.8', ka: 'ლამბერტ-იტონის მიასთენიური სინდრომი', en: 'Lambert–Eaton myasthenic syndrome',
  desc: 'ნერვ-კუნთოვანი გადაცემის აუტოიმუნური დაავადება, პრესინაფსური დაზიანებით: ანტისხეულები P/Q-ტიპის ძაბვადამოკიდებული Ca²⁺ არხების წინააღმდეგ. დაახლოებით 50–60%-ში პარანეოპლაზიურია, ძირითადად წვრილუჯრედოვანი ფილტვის კიბოს ფონზე. მიასთენიისგან განსხვავებით, ძალა მოკლე დატვირთვის შემდეგ მატულობს.',
  show: ['cortex', 'cerebellum', 'stem', 'cranial', 'cord', 'spinal', 'legs', 'muscle', 'bone', 'skin'], op: { bone: .12 },
  steps: [
    { t: 'ანტისხეულები Ca²⁺ არხების წინააღმდეგ', x: 'წვრილუჯრედოვანი ფილტვის კიბოს უჯრედები ძაბვადამოკიდებულ Ca²⁺ არხებს გამოხატავენ. მათ წინააღმდეგ წარმოქმნილი ანტისხეულები ჯვარედინად უკავშირდება მოტორული ნერვის ტერმინალის P/Q-ტიპის არხებს (მოლეკულური მიმიკრია). არაპარანეოპლაზიური ფორმა ხშირად სხვა აუტოიმუნურ დაავადებებთან ერთად გვხვდება.',
      fx: { micro: { view: 'lems', anim: 'lems_ab' } } },
    { t: 'Ca²⁺-ის შემოსვლის შემცირება', x: 'ანტისხეულები Ca²⁺ არხებს ერთმანეთთან აკავშირებს და მათ ინტერნალიზაციას იწვევს. აქტიურ ზონაში არხები მცირდება. ერთი მოქმედების პოტენციალისას ნაკლები Ca²⁺ შემოდის, ერწყმის ნაკლები ვეზიკულა და ACh-ის კვანტური რაოდენობა მცირდება. პოსტსინაფსური რეცეპტორები ნორმალურია.',
      fx: { micro: { view: 'lems', anim: 'lems_lowca' } } },
    { t: 'დაბალი EPP და ფასილიტაცია', x: 'ცალკეული იმპულსის შემდეგ ბოლო ფირფიტის პოტენციალი დაბალია და ბევრი ბოჭკო არ იკუმშება. მაღალი სიხშირის სტიმულაციისას (20–50 Hz) ან 10 წამიანი მაქსიმალური ნებითი შეკუმშვის შემდეგ ტერმინალში ნარჩენი Ca²⁺ გროვდება, გამოყოფა იზრდება და EPP ზღურბლს აღწევს. ENMG-ზე CMAP-ის ამპლიტუდა დაბალია და მატულობს >100%-ით (ინკრემენტი).',
      fx: { micro: { view: 'lems', anim: 'lems_facil' }, chart: 'epp' } },
    { t: 'კლინიკა: პროქსიმალური სისუსტე + ავტონომიური ნიშნები', x: 'ძირითადად ზიანდება ქვედა კიდურების პროქსიმალური კუნთები (კიბეზე ასვლა, სკამიდან ადგომა). რეფლექსები დაქვეითებულია და დატვირთვის შემდეგ დროებით აღდგება. ავტონომიური დისფუნქცია ვლინდება პირის სიმშრალით, ყაბზობით და ერექციული დისფუნქციით. პტოზი და დიპლოპია მიასთენიაზე ნაკლებად გამოხატულია.',
      fx: { cam: 'legs', show: ['cord', 'spinal', 'legs', 'muscle', 'bone'], hl: [{ m: '(rectus femoris|vastus|gluteus|biceps femoris|semitendinosus)', c: 'amber', g: ['muscle'] }, { m: '(deltoid|biceps brachii|triceps brachii)', c: 'amber', g: ['muscle'] }], dim: true } },
  ],
  clin: ['პროქსიმალური, ძირითადად ქვედა კიდურების სისუსტე', 'ჰიპო/არეფლექსია; ძალა და რეფლექსები დატვირთვის შემდეგ დროებით მატულობს', 'ავტონომიური: პირის სიმშრალე, ყაბზობა, ერექციული დისფუნქცია', 'დიაგნოზი: anti-P/Q VGCC ანტისხეულები; RNS: დაბალი CMAP და >100% ინკრემენტი', 'სიმსივნის ძიება: გულმკერდის CT / PET-CT (წვრილუჯრედოვანი კიბო); განმეორებითი სკრინინგი ≈ 2 წლის განმავლობაში', 'მკურნალობა: ამიფამპრიდინი (Amifampridine, 3,4-DAP): K⁺ არხების ბლოკადა → ახანგრძლივებს AP-ს → ↑ Ca²⁺ შემოსვლა; პირიდოსტიგმინი (Pyridostigmine) — დამატებით; იმუნოთერაპია; სიმსივნის მკურნალობა'],
  refs: [['StatPearls: Lambert-Eaton Myasthenic Syndrome', SB('Lambert-Eaton myasthenic syndrome')], ['LEMS — diagnosis and treatment review', PM('Lambert-Eaton myasthenic syndrome diagnosis treatment review')]],
},
{
  id: 'gbs', grp: 'pns', icd: 'G61.0', ka: 'გიენ-ბარეს სინდრომი', en: 'Guillain–Barré syndrome',
  desc: 'მწვავე იმუნური პოლირადიკულონევროპათია. სწრაფად, დღეების ან კვირების განმავლობაში, ვითარდება აღმავალი სიმეტრიული დუნე სისუსტე და არეფლექსია. სუნთქვის კუნთების ჩართვის გამო საჭიროებს მონიტორინგს.',
  show: ['cortex', 'cerebellum', 'stem', 'cord', 'spinal', 'legs', 'cranial', 'bone', 'muscle', 'skin'], op: { bone: .1 },
  steps: [
    { t: 'წინამორბედი ინფექცია', x: 'დაავადებამდე 1–4 კვირით ადრე ხშირად გადატანილია ინფექცია: Campylobacter jejuni, CMV, EBV, Mycoplasma, Zika ან სხვა. იშვიათად წინ უსწრებს ვაქცინაცია ან ოპერაცია.',
      fx: { cam: 'body', hl: [], dim: true } },
    { t: 'მოლეკულური მიმიკრია', x: 'მიკრობის ანტიგენებსა და ნერვის განგლიოზიდებს (GM1, GD1a, GQ1b) შორის მსგავსების გამო წარმოიქმნება ჯვარედინი ანტისხეულები. AIDP ფორმაში მიელინს კომპლემენტი და მაკროფაგები აზიანებს; AMAN ფორმაში (anti-GM1) სამიზნე რანვიეს კვანძის აქსოლემაა.',
      fx: { cam: 'lumbar', show: ['cord', 'spinal', 'legs', 'bone'], op: { bone: .2 }, hl: [{ m: 'cauda|root', c: 'amber' }], dim: true } },
    { t: 'აღმავალი გატარების ბლოკი', x: 'ფესვებსა და პერიფერიულ ნერვებში გატარება ბლოკირდება. სისუსტე, როგორც წესი, ფეხებიდან იწყება და ზემოთ ადის. ღრმა მყესოვანი რეფლექსები ქრება.',
      fx: { cam: 'body', show: ['cortex', 'cerebellum', 'stem', 'cord', 'spinal', 'legs', 'cranial', 'bone', 'muscle'], op: { bone: .1 }, spread: { g: ['legs', 'spinal', 'muscle'], from: 0.0, to: 1.45, dur: 7, c: 'red' } } },
    { t: 'რესპირაციული და ავტონომიური ჩართვა', x: 'დიაფრაგმის ნერვის (C3–C5) და ბულბური ნერვების ჩართვისას ვითარდება სუნთქვის უკმარისობა; პაციენტების დაახლოებით მეოთხედს მექანიკური ვენტილაცია სჭირდება. ავტონომიური დისფუნქცია იწვევს არითმიას და არტერიული წნევის რყევას.',
      fx: { cam: 'neck', show: ['stem', 'cord', 'spinal', 'cranial', 'bone', 'cerebellum'], op: { bone: .15 }, hl: [{ m: 'phrenic', c: 'red' }, { m: 'vagus|glossopharyngeal|hypoglossal|facial', c: 'amber' }], dim: true } },
  ],
  clin: ['აღმავალი, სიმეტრიული, დუნე სისუსტე', 'არეფლექსია ან ჰიპორეფლექსია', 'პარესთეზიები, რადიკულური ან ზურგის ტკივილი', 'ორმხრივი სახის სისუსტე, ბულბური ნიშნები', 'სუნთქვის მონიტორინგი: FVC, NIF; „20/30/40 წესი"', 'ლიქვორი: ცილოვან-უჯრედული დისოციაცია; ENMG: დემიელინიზაცია ან აქსონოპათია', 'მკურნალობა: ინტრავენური იმუნოგლობულინი (IVIG) ან პლაზმაფერეზი'],
  refs: [['StatPearls: Guillain-Barré Syndrome', SB('Guillain Barre syndrome')], ['Leonhard et al. 2019, Nat Rev Neurol — diagnosis and management', PM('Leonhard diagnosis and management of Guillain-Barre syndrome in ten steps')]],
},
{
  id: 'cts', grp: 'pns', icd: 'G56.0', ka: 'მაჯის არხის სინდრომი', en: 'Carpal tunnel syndrome',
  desc: 'მედიანური ნერვის კომპრესია მაჯის არხში, მომხრელთა შემაკავებლის (retinaculum flexorum) ქვეშ. ყველაზე ხშირი კომპრესიული მონონევროპათიაა.',
  show: ['spinal', 'bone', 'muscle', 'skin', 'cord'], op: { bone: .35, muscle: .35 },
  steps: [
    { t: 'რისკ-ფაქტორები', x: 'მაჯის განმეორებითი მოხრა-გაშლა, ვიბრაცია, ორსულობა, ჰიპოთირეოზი, შაქრიანი დიაბეტი, რევმატოიდული ართრიტი, ამილოიდოზი, სიმსუქნე და აკრომეგალია ზრდის არხის შიგთავსს ან ნერვის მოწყვლადობას.',
      fx: { cam: 'handL', hl: [{ m: 'left (median|lateral proper|medial proper)|median nerve to middle', c: 'amber' }], lesion: [{ at: { snap: 'left median nerve', to: [0.255, 0.885, 0.035] }, r: .007, c: 'amber' }], dim: true } },
    { t: 'წნევა არხში → იშემია', x: 'არხის შიგნით წნევა მატულობს, განსაკუთრებით მაჯის მოხრისას და ღამით. ეპინევრიუმის ვენური ცირკულაცია ფერხდება, ვითარდება შეშუპება და ნერვის იშემია. ეს ხსნის ღამის პარესთეზიებს და ხელის ფერთხვით შვებას.',
      fx: { cam: 'handL', hl: [{ m: 'left median nerve', c: 'red', where: { near: [0.255, 0.885, 0.035], r: .03 } }], lesion: [{ at: { snap: 'left median nerve', to: [0.255, 0.885, 0.035] }, r: .009 }], dim: true } },
    { t: 'დემიელინიზაცია → გატარების შენელება', x: 'ფოკალური დემიელინიზაცია ანელებს გატარებას. ENMG-ზე ვლინდება დისტალური მოტორული და სენსორული ლატენტობის გახანგრძლივება. ხანგრძლივი კომპრესია აქსონურ დაზიანებამდე მიდის.',
      fx: { cam: 'handL', hl: [{ m: 'left median nerve', c: 'red', where: { below: 0.9 } }, { m: 'left (lateral proper|medial proper) palmar digital branch .*median|median nerve to middle', c: 'red' }], flow: [{ path: [{ snap: 'left median nerve', to: [0.235, 1.0, 0.02] }, { snap: 'left median nerve', to: [0.255, 0.885, 0.035] }, { snap: 'left median nerve', to: [0.27, 0.86, 0.04] }], c: 'amber', block: 1, slow: 1 }], dim: true } },
    { t: 'ტენარის ატროფია', x: 'მოტორული ბოჭკოების დაზიანებისას ტენარის კუნთები (m. abductor pollicis brevis, m. opponens pollicis) სუსტდება და ატროფირდება. ცერის განზიდვა და ოპოზიცია ძნელდება.',
      fx: { cam: 'handL', show: ['spinal', 'bone', 'muscle'], hl: [{ m: 'left median nerve', c: 'red', where: { below: 0.9 } }], atrophy: [{ m: 'left (abductor pollicis brevis|opponens pollicis)|superficial head of left flexor pollicis', k: .75 }], grey: [{ m: 'left (abductor pollicis brevis|opponens pollicis)|superficial head of left flexor pollicis', g: ['muscle'] }], dim: true } },
  ],
  clin: ['პარესთეზია და დაბუჟება I–III თითსა და IV თითის რადიალურ ნახევარში', 'ღამით გაძლიერება; შვება ხელის ფერთხვით ("flick sign")', 'ტინელის ნიშანი მაჯაზე; ფალენის ტესტი', 'ტენარის ატროფია, ცერის განზიდვის სისუსტე', 'ხელისგულის კანი (palmar cutaneous branch) ზოგადად შენარჩუნებულია, რადგან ეს ტოტი არხის ზემოთ გამოდის', 'ENMG ადასტურებს დიაგნოზს და აფასებს სიმძიმეს'],
  refs: [['StatPearls: Carpal Tunnel Syndrome', SB('carpal tunnel syndrome')], ['AAOS Clinical Practice Guideline: CTS', PM('AAOS clinical practice guideline carpal tunnel syndrome')]],
},
{
  id: 'cubital', grp: 'pns', icd: 'G56.2', ka: 'იდაყვის არხის სინდრომი', en: 'Cubital tunnel syndrome (ulnar neuropathy at the elbow)',
  desc: 'იდაყვის ნერვის კომპრესია ან დაჭიმვა მედიალური ეპიკონდილის უკან, იდაყვის არხში. ზედა კიდურის მეორე ყველაზე ხშირი კომპრესიული ნევროპათიაა.',
  show: ['spinal', 'bone', 'muscle', 'skin'], op: { bone: .35, muscle: .4 },
  steps: [
    { t: 'ანატომიური მოწყვლადობა', x: 'მედიალური ეპიკონდილის უკან ნერვი ზედაპირულად და ძვალთან ახლოს გადის, ოსბორნის ლიგამენტის ქვეშ. იდაყვის მოხრისას არხის მოცულობა მცირდება, ხოლო ნერვი იჭიმება და იკუმშება.',
      fx: { cam: 'elbowL', hl: [{ m: 'left ulnar nerve', c: 'amber' }], lesion: [{ at: { snap: 'left ulnar nerve', to: [0.2, 1.12, -0.04] }, r: .007, c: 'amber' }], dim: true } },
    { t: 'კომპრესია და ტრაქცია', x: 'ხანგრძლივი მოხრა (ტელეფონი, ძილი), იდაყვზე დაყრდნობა, ოსტეოფიტები და ნერვის სუბლუქსაცია იწვევს ფოკალურ იშემიას და დემიელინიზაციას.',
      fx: { cam: 'elbowL', hl: [{ m: 'left ulnar nerve', c: 'red', where: { near: [0.2, 1.12, -0.04], r: .035 } }], lesion: [{ at: { snap: 'left ulnar nerve', to: [0.2, 1.12, -0.04] }, r: .009 }], dim: true } },
    { t: 'გატარების ბლოკი დისტალურად', x: 'იმპულსი ნელდება ან ბლოკირდება იდაყვის სეგმენტზე. დისტალურად ზიანდება მტევნის შიგნითა კუნთების უმეტესობა და IV–V თითის მგრძნობელობა.',
      fx: { cam: 'armL', hl: [{ m: 'left ulnar nerve', c: 'red', where: { below: 1.13 } }], flow: [{ path: [{ snap: 'left ulnar nerve', to: [0.18, 1.3, -0.03] }, { snap: 'left ulnar nerve', to: [0.2, 1.12, -0.04] }, { snap: 'left ulnar nerve', to: [0.24, 0.9, 0.02] }], c: 'amber', block: 1 }], dim: true } },
    { t: 'მტევნის შიგნითა კუნთების ატროფია', x: 'ძვალთაშუა კუნთები, ჰიპოთენარი და III–IV ჭიაყელასებრი კუნთები ატროფირდება. ჩნდება „კლანჭისებრი" IV–V თითი და ფრომენის ნიშანი (m. adductor pollicis-ის სისუსტე).',
      fx: { cam: 'handL', show: ['spinal', 'bone', 'muscle'], hl: [{ m: 'left ulnar nerve', c: 'red', where: { below: 1.13 } }], atrophy: [{ m: 'interossei of left|abductor digiti minimi of left|lumbricals of left', k: .75 }], grey: [{ m: 'interossei of left|abductor digiti minimi of left|lumbricals of left|left flexor carpi ulnaris|of left flexor carpi ulnaris', g: ['muscle'] }], dim: true } },
  ],
  clin: ['პარესთეზია IV–V თითში (IV-ის ულნარულ ნახევარში)', 'ტინელის ნიშანი იდაყვის არხზე; იდაყვის მოხრის ტესტი', 'ფრომენის ნიშანი, ვარტენბერგის ნიშანი', 'პირველი ძვალთაშუა სივრცის ატროფია', 'გვიანდელი: „კლანჭისებრი" მტევანი (IV–V)', 'ENMG: გატარების შენელება იდაყვის სეგმენტზე'],
  refs: [['StatPearls: Cubital Tunnel Syndrome', SB('cubital tunnel syndrome')], ['StatPearls: Ulnar Neuropathy', SB('ulnar nerve entrapment')]],
},
{
  id: 'radial', grp: 'pns', icd: 'G56.3', ka: 'სხივის ნერვის დაზიანება (სპირალური ღარი)', en: 'Radial neuropathy at the spiral groove',
  desc: 'სხივის ნერვის დაზიანება მხრის ძვლის სპირალურ ღარში, მხრის ძვლის მოტეხილობის ან ხანგრძლივი ზეწოლის („შაბათი ღამის დამბლა") დროს. მთავარი ნიშანია „ჩამოკიდებული მტევანი".',
  show: ['spinal', 'bone', 'muscle', 'skin'], op: { bone: .35, muscle: .4 },
  steps: [
    { t: 'მიზეზი', x: 'მხრის ძვლის დიაფიზის მოტეხილობა (მათ შორის დისტალური მესამედის — ჰოლშტაინ-ლუისის), ხანგრძლივი ზეწოლა ალკოჰოლური ან ღრმა ძილის დროს, ტურნიკეტი. ნერვი მხრის შუა მესამედში უშუალოდ ძვალს ეკვრის.',
      fx: { cam: 'humerusL', hl: [{ m: 'left humerus', c: 'amber', g: ['bone'] }, { m: 'left radial|posterior cord of left', c: 'amber' }], lesion: [{ at: [0.185, 1.25, -0.04], r: .008, c: 'amber' }], dim: true } },
    { t: 'ნეიროპრაქსია ან აქსონოტმეზისი', x: 'ზეწოლა იწვევს ფოკალურ დემიელინიზაციას (ნეიროპრაქსია), რაც კვირებში აღდგება. მოტეხილობამ შეიძლება ნერვი დაჭიმოს ან გაწყვიტოს (აქსონოტმეზისი ან ნეიროტმეზისი), რაც უოლერის დეგენერაციას და ხანგრძლივ აღდგენას ნიშნავს.',
      fx: { cam: 'humerusL', hl: [{ m: 'left radial|posterior cord of left', c: 'red', where: { below: 1.26 } }], lesion: [{ at: [0.185, 1.25, -0.04], r: .01 }], dim: true } },
    { t: 'ტრიცეპსი შენარჩუნებულია', x: 'ტრიცეპსის ტოტები ნერვს სპირალურ ღარამდე, უფრო პროქსიმალურად, სცილდება. ამიტომ იდაყვის გაშლა ძირითადად შენარჩუნებულია, რაც ეხმარება დაზიანების დონის დადგენას.',
      fx: { cam: 'humerusL', show: ['spinal', 'bone', 'muscle'], op: { bone: .3 }, hl: [{ m: 'triceps brachii', c: 'green', g: ['muscle'] }, { m: 'left radial|posterior cord of left', c: 'red', where: { below: 1.26 } }], dim: true } },
    { t: '„ჩამოკიდებული მტევანი"', x: 'მაჯისა და თითების ყველა გამშლელი დუნდება: m. extensor carpi radialis longus/brevis, m. extensor digitorum, m. extensor carpi ulnaris, აგრეთვე m. brachioradialis. მტევანი ჩამოკიდებულია და თითების ძირითადი ფალანგების გაშლა შეუძლებელია.',
      fx: { cam: 'armL', show: ['spinal', 'bone', 'muscle'], hl: [{ m: 'left radial', c: 'red', where: { below: 1.26 } }], grey: [{ m: 'left (extensor carpi radialis|extensor digitorum|extensor carpi ulnaris|brachioradialis)', g: ['muscle'] }], atrophy: [{ m: 'left (extensor carpi radialis|extensor digitorum|extensor carpi ulnaris|brachioradialis)', k: .85 }], dim: true } },
  ],
  clin: ['„ჩამოკიდებული მტევანი" (wrist drop)', 'თითების ძირითადი ფალანგების გაშლის სისუსტე', 'მგრძნობელობის დაქვეითება I–II თითის ზურგზე (ანატომიური „სათუთუნე")', 'იდაყვის გაშლა შენარჩუნებულია (სპირალური ღარის დონე)', 'ზეწოლის შემთხვევაში აღდგენა კვირებში', 'მოტეხილობისას — პირველადი დაკვირვება; ENMG 3–4 კვირის შემდეგ'],
  refs: [['StatPearls: Radial Nerve Injury', SB('radial nerve injury')], ['StatPearls: Radial Neuropathy', SB('radial neuropathy')]],
},
{
  id: 'disc', grp: 'pns', icd: 'M51.1', ka: 'L5–S1 დისკის თიაქარი S1 რადიკულოპათიით (იშიასი)', en: 'L5–S1 disc herniation with S1 radiculopathy',
  desc: 'დისკის გულგულოვანი ბირთვი ფიბროზული რგოლის ნაპრალში გამოდის და S1 ფესვს კუმშავს და აღიზიანებს. შედეგად ტკივილი საჯდომი ნერვის გასწვრივ ირადიირებს, ფეხის უკანა ზედაპირით ტერფამდე.',
  show: ['cord', 'spinal', 'legs', 'bone', 'disc'], op: { bone: .25 },
  steps: [
    { t: 'დისკის დეგენერაცია', x: 'ასაკთან ერთად ბირთვი დეჰიდრატირდება და პროტეოგლიკანებს კარგავს. ფიბროზულ რგოლში რადიალური ნაპრალები ჩნდება. L4–L5 და L5–S1 ყველაზე დატვირთული დონეებია.',
      fx: { cam: 'lumbar', show: ['cord', 'bone', 'disc', 'legs'], op: { bone: .35 }, hl: [{ m: 'fifth lumbar', c: 'amber', g: ['disc'] }], dim: true } },
    { t: 'პოსტეროლატერალური პროლაფსი', x: 'ბირთვი ყველაზე ხშირად პოსტეროლატერალურად გამოდის, სადაც უკანა გრძივი იოგი ყველაზე სუსტია. L5–S1 დონეზე ასეთი თიაქარი ძირითადად გამავალ (traversing) S1 ფესვს აზიანებს.',
      fx: { cam: 'lumbar', hl: [{ m: 'fifth lumbar', c: 'red', g: ['disc'] }, { m: 'left lumbosacral root s1', c: 'amber' }], lesion: [{ at: { c: 'intervertebral disk of fifth lumbar', dx: 0.012, dz: -0.02 }, r: .008 }], dim: true } },
    { t: 'მექანიკური + ქიმიური დაზიანება', x: 'ფესვს მექანიკური კომპრესიის გარდა ბირთვის ანთებითი მედიატორებიც აზიანებს: TNF-α, IL-1β, IL-6, ფოსფოლიპაზა A2. ვითარდება ფესვის შეშუპება, დორსალური განგლიონის სენსიბილიზაცია და ექტოპიური განმუხტვები, რასაც რადიკულური ტკივილი მოსდევს.',
      fx: { cam: 'lumbar', hl: [{ m: 'left lumbosacral root s1', c: 'red' }, { m: 'fifth lumbar', c: 'red', g: ['disc'] }], lesion: [{ at: { c: 'intervertebral disk of fifth lumbar', dx: 0.012, dz: -0.02 }, r: .008 }], wave: { at: { c: 'intervertebral disk of fifth lumbar', dx: 0.012, dz: -0.02 }, r: .014, c: 'amber' }, dim: true } },
    { t: 'ტკივილის ირადიაცია S1 დერმატომში', x: 'ტკივილი დუნდულიდან ბარძაყის და წვივის უკანა ზედაპირით ტერფის ლატერალურ კიდემდე ვრცელდება. ტერფის პლანტარული ფლექსია სუსტდება (m. gastrocnemius, m. soleus) და აქილევსის რეფლექსი ქვეითდება.',
      fx: { cam: 'legBack', show: ['cord', 'spinal', 'legs', 'bone', 'disc', 'muscle'], op: { bone: .2 }, hl: [{ m: 'left (lumbosacral root s1|sciatic|tibial)', c: 'red' }], grey: [{ m: 'left gastrocnemius|of left gastrocnemius|left soleus', g: ['muscle'] }], flow: [{ path: 'legL_S1', c: 'red' }], dim: true } },
  ],
  clin: ['რადიკულური ტკივილი: დუნდული → ბარძაყის/წვივის უკანა ზედაპირი → ტერფის ლატერალური კიდე', 'ლასეგის (SLR) სიმპტომი დადებითი', 'აქილევსის რეფლექსის დაქვეითება ან გაქრობა (S1)', 'პლანტარული ფლექსიის სისუსტე (თითის წვერებზე სიარული)', '„წითელი დროშები": კაუდა ეკვინას სინდრომი (შარდის შეკავება, ანოგენიტალური ანესთეზია) — სასწრაფო MRI', 'უმეტესობა კონსერვატიულად უმჯობესდება 6–12 კვირაში'],
  refs: [['StatPearls: Lumbar Disc Herniation', SB('lumbar disc herniation')], ['StatPearls: Lumbosacral Radiculopathy', SB('lumbosacral radiculopathy')]],
},
{
  id: 'fibular', grp: 'pns', icd: 'G57.3', ka: 'საერთო მცირე წვივის ნერვის ნევროპათია', en: 'Common fibular (peroneal) neuropathy at the fibular head',
  desc: 'საერთო მცირე წვივის ნერვის კომპრესია მცირე წვივის ძვლის თავისა და ყელის დონეზე. ქვედა კიდურის ყველაზე ხშირი მონონევროპათიაა, რომელიც „ჩამოკიდებულ ტერფს" იწვევს.',
  show: ['legs', 'bone', 'muscle', 'skin', 'cord'], op: { bone: .35 },
  steps: [
    { t: 'ზედაპირული მიმდინარეობა', x: 'ნერვი საჯდომი ნერვიდან გამოყოფის შემდეგ მცირე წვივის ძვლის ყელს ეხვევა. ამ ადგილას ის მხოლოდ კანით და კანქვეშა ქსოვილით არის დაფარული.',
      fx: { cam: 'kneeL', show: ['legs', 'bone', 'muscle'], op: { bone: .4, muscle: .3 }, hl: [{ m: 'left fibula', c: 'amber', g: ['bone'] }, { m: 'left common fibular', c: 'amber' }], lesion: [{ at: { snap: 'left common fibular', to: [0.122, 0.415, -0.02] }, r: .007, c: 'amber' }], dim: true } },
    { t: 'კომპრესია', x: 'ფეხის ფეხზე გადადება, სწრაფი წონის კლება (ცხიმოვანი ბალიშის დაკარგვა), ხანგრძლივი ჩაცუცქვა, თაბაშირი ან ორთეზი და წოლითი მდგომარეობა ოპერაციისას ნერვს ძვალზე აჭერს. ვითარდება ფოკალური დემიელინიზაცია ან აქსონური დაზიანება.',
      fx: { cam: 'kneeL', hl: [{ m: 'left common fibular', c: 'red', where: { near: [0.122, 0.415, -0.02], r: .04 } }], lesion: [{ at: { snap: 'left common fibular', to: [0.122, 0.415, -0.02] }, r: .009 }], dim: true } },
    { t: 'ბლოკი ღრმა და ზედაპირულ ტოტებში', x: 'ღრმა ტოტი წინა კომპარტმენტს ინერვირებს (m. tibialis anterior, m. extensor digitorum longus, m. extensor hallucis longus), ანუ დორსიფლექსიას. ზედაპირული ტოტი ინერვირებს m. fibularis longus/brevis-ს, ანუ ევერსიას.',
      fx: { cam: 'legL', show: ['legs', 'bone', 'muscle'], op: { bone: .3 }, hl: [{ m: 'left common fibular', c: 'red', where: { below: 0.43 } }], grey: [{ m: 'left (tibialis anterior|extensor digitorum longus|extensor hallucis longus|fibularis)', g: ['muscle'] }], flow: [{ path: 'legL_fib', c: 'amber', block: 1 }], dim: true } },
    { t: '„ჩამოკიდებული ტერფი" და დიფერენცირება', x: 'ტერფის დორსიფლექსია შეუძლებელია, ამიტომ პაციენტი მუხლს მაღლა სწევს („მამლის სიარული", steppage). L5 რადიკულოპათიისგან განსხვავებით, ტერფის ინვერსია (m. tibialis posterior, დიდი წვივის ნერვი) და ბარძაყის განზიდვა შენარჩუნებულია.',
      fx: { cam: 'legL', show: ['legs', 'bone', 'muscle'], hl: [{ m: 'left common fibular', c: 'red', where: { below: 0.43 } }, { m: 'left tibial', c: 'green' }], atrophy: [{ m: 'left (tibialis anterior|extensor digitorum longus|extensor hallucis longus|fibularis)', k: .85 }], grey: [{ m: 'left (tibialis anterior|extensor digitorum longus|extensor hallucis longus|fibularis)', g: ['muscle'] }], dim: true } },
  ],
  clin: ['„ჩამოკიდებული ტერფი" (foot drop), „მამლის სიარული"', 'ევერსიის სისუსტე', 'მგრძნობელობის დაქვეითება წვივის ანტეროლატერალურ ზედაპირსა და ტერფის ზურგზე (I–II თითშორისი სივრცე — ღრმა ტოტი)', 'ინვერსია და აქილევსის რეფლექსი შენარჩუნებულია (L5 რადიკულოპათიისგან განსხვავებით)', 'ტინელის ნიშანი მცირე წვივის ძვლის ყელთან', 'ENMG: გატარების ბლოკი მცირე წვივის ძვლის თავის დონეზე'],
  refs: [['StatPearls: Peroneal Nerve Injury', SB('common peroneal nerve injury')], ['StatPearls: Foot Drop', SB('foot drop')]],
},
];
